# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aritcle',
            name='title',
            field=models.CharField(max_length=101),
        ),
    ]
