# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publish Date'),
        ),
    ]
