# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170526_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f9f7b36-7bef-4c49-985b-19fb356a54b4'), primary_key=True, serialize=False),
        ),
    ]
